# Generated by Django 5.0.1 on 2026-01-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.AddField(
            model_name='subject',
            name='faculties',
            field=models.ManyToManyField(related_name='subjects', to='adminpanel.faculty'),
        ),
    ]
