# Generated by Django 5.0.1 on 2026-01-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_subject_faculty_subject_faculties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculties',
        ),
    ]
