# Generated by Django 5.0.1 on 2026-01-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_remove_subject_faculties'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subject')),
            ],
            options={
                'unique_together': {('subject', 'faculty')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='subjects', through='adminpanel.SubjectFaculty', to='adminpanel.faculty'),
        ),
    ]
