# Generated by Django 5.0.1 on 2026-01-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_subjectfaculty_subject_faculties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_code',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='course_name',
        ),
    ]
