# Generated by Django 5.0.1 on 2026-01-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_rename_subject_code_subject_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
