# Generated by Django 5.0.1 on 2026-01-22 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_subject_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po1', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po2', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po3', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po4', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po5', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po6', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po7', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po8', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po9', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po10', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po11', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('po12', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('pso1', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('pso2', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('course_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='adminpanel.courseoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_lecture', models.PositiveIntegerField(default=0)),
                ('hours_practical', models.PositiveIntegerField(default=0)),
                ('hours_tutorial', models.PositiveIntegerField(default=0)),
                ('credit_lecture', models.PositiveIntegerField(default=0)),
                ('credit_practical', models.PositiveIntegerField(default=0)),
                ('credit_tutorial', models.PositiveIntegerField(default=0)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Core', 'Core'), ('Elective', 'Elective'), ('Foundation', 'Foundation')], default='Core', max_length=50)),
                ('focus', models.CharField(choices=[('Employability', 'Employability'), ('Entrepreneurship', 'Entrepreneurship'), ('Skill', 'Skill Development')], default='Employability', max_length=50)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final Submission')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabi', to='adminpanel.faculty')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='adminpanel.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('weightage', models.PositiveIntegerField(help_text='Percentage weightage')),
                ('hours', models.PositiveIntegerField()),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicals', to='adminpanel.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_sem', models.PositiveIntegerField(default=0)),
                ('end_sem', models.PositiveIntegerField(default=0)),
                ('cec_attendance', models.PositiveIntegerField(default=0)),
                ('cec_mcq', models.PositiveIntegerField(default=0)),
                ('cec_assignment', models.PositiveIntegerField(default=0)),
                ('prac_attendance', models.PositiveIntegerField(default=0)),
                ('prac_exam', models.PositiveIntegerField(default=0)),
                ('prac_viva', models.PositiveIntegerField(default=0)),
                ('prac_journal', models.PositiveIntegerField(default=0)),
                ('prac_discipline', models.PositiveIntegerField(default=0)),
                ('syllabus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scheme', to='adminpanel.syllabus')),
            ],
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outcomes', to='adminpanel.syllabus'),
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='adminpanel.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weightage', models.PositiveIntegerField(help_text='Percentage weightage')),
                ('hours', models.PositiveIntegerField()),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_units', to='adminpanel.syllabus')),
            ],
        ),
    ]
