# Generated by Django 5.0.1 on 2026-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_courseoutcome_outcomemapping_syllabus_practical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus_pdfs/'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
