# Generated by Django 5.0.1 on 2026-01-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_syllabus_pdf_file_syllabus_pdf_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='adminpanel.syllabus')),
            ],
        ),
    ]
