# Generated by Django 5.0.1 on 2026-02-04 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_syllabus_pdf_file_learningresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='adminpanel.program')),
            ],
            options={
                'unique_together': {('program', 'semester_number')},
            },
        ),
        migrations.CreateModel(
            name='SemesterFacultyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_access', to='adminpanel.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_access', to='adminpanel.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='adminpanel.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_allocations', to='adminpanel.subject')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('semester', 'subject')},
            },
        ),
    ]
