# Generated by Django 5.0.1 on 2026-02-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_subject_program_subject_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.branch'),
        ),
    ]
