# Generated by Django 5.0.1 on 2026-02-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_subject_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='semester_pdfs/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.branch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_pdfs', to='adminpanel.semester')),
            ],
            options={
                'unique_together': {('semester', 'branch')},
            },
        ),
    ]
