# Generated by Django 5.0.1 on 2026-02-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_semesterreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterreference',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
