# Generated by Django 5.0.1 on 2026-02-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_semesterreference_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
