# Generated by Django 5.0.1 on 2026-02-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_faculty_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterreference',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
