# Generated by Django 5.0.1 on 2026-02-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_semesterreference_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.CharField(default='2025-26', help_text='Format: YYYY-YY (e.g. 2025-26)', max_length=20),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='category',
            field=models.CharField(choices=[('HS', 'HS'), ('BS', 'BS'), ('ES', 'ES'), ('PC', 'PC'), ('PE', 'PE'), ('OE', 'OE'), ('IP', 'IP'), ('NC', 'NC')], default='HS', max_length=50),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='focus',
            field=models.CharField(choices=[('HS', 'Humanities and Social Sciences (HS)'), ('BS', 'Basic Sciences (BS)'), ('ES', 'Engineering Sciences (ES)'), ('PC', 'Professional Subjects – Core (PC)'), ('PE', 'Professional Subjects – Electives (PE)'), ('OE', 'Open Subjects – Electives (OE)'), ('IP', 'Project Work / Seminar / Internship'), ('NC', 'Mandatory Courses – Non Credit'), ('VAC', 'Value Added Courses')], default='HS', max_length=150, verbose_name='Course Category Title'),
        ),
    ]
