# Generated by Django 5.0.1 on 2026-04-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_subject_academic_year_alter_syllabus_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. PO1, PO2, ...', max_length=20)),
                ('description', models.TextField(help_text='Outcome description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_outcomes', to='adminpanel.program')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('program', 'code')},
            },
        ),
    ]
