# Generated by Django 5.0.1 on 2026-04-07 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_add_program_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSpecificOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. PSO1, PSO2, ...', max_length=20)),
                ('description', models.TextField(help_text='Outcome description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_specific_outcomes', to='adminpanel.branch')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('branch', 'code')},
            },
        ),
    ]
