# Generated by Django 5.0.1 on 2026-04-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_add_program_specific_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEducationalObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. PEO1, PEO2, ...', max_length=20)),
                ('description', models.TextField(help_text='Objective description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_educational_objectives', to='adminpanel.program')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('program', 'code')},
            },
        ),
    ]
