# Generated by Django 6.0.5 on 2026-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_add_program_educational_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='course_focus',
            field=models.CharField(choices=[('Employability', 'Employability'), ('Entrepreneurship', 'Entrepreneurship'), ('Skill Development', 'Skill Development')], default='Employability', max_length=50),
        ),
    ]
