# Generated by Django 6.0.5 on 2026-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_syllabus_course_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseobjective',
            name='blooms_domain',
            field=models.CharField(blank=True, choices=[('Cognitive', 'Cognitive'), ('Affective', 'Affective'), ('Psychomotor', 'Psychomotor')], max_length=20, null=True, verbose_name="Bloom's Taxonomy Domain"),
        ),
        migrations.AddField(
            model_name='courseobjective',
            name='blooms_subdomain',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name="Bloom's Taxonomy Subdomain"),
        ),
    ]
