# Generated by Django 5.0 on 2026-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0022_add_blooms_to_courseobjective"),
    ]

    operations = [
        migrations.AddField(
            model_name="syllabus",
            name="last_completed_slide",
            field=models.IntegerField(default=0),
        ),
    ]
