# Generated by Django 5.0 on 2026-07-29 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminpanel", "0023_syllabus_last_completed_slide"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyllabusEditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the change was made",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the user making the change",
                        null=True,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("status_change", "Status Change"),
                            ("bulk_update", "Bulk Update"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the model being changed (e.g., Syllabus, CourseObjective)",
                        max_length=100,
                    ),
                ),
                (
                    "record_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the specific record that was modified",
                        null=True,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the field that was changed",
                        max_length=100,
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True,
                        help_text="Previous value before the change",
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="New value after the change", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the change"
                    ),
                ),
                (
                    "syllabus",
                    models.ForeignKey(
                        help_text="The syllabus being modified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_logs",
                        to="adminpanel.syllabus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the change (preserved even if user is deleted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="syllabus_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Syllabus Edit Log",
                "verbose_name_plural": "Syllabus Edit Logs",
                "ordering": ["-timestamp"],
                "permissions": [("view_all_logs", "Can view all audit logs")],
                "indexes": [
                    models.Index(
                        fields=["syllabus", "-timestamp"],
                        name="accounts_sy_syllabu_081899_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="accounts_sy_user_id_ddb8bb_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="accounts_sy_timesta_ad2849_idx"
                    ),
                ],
            },
        ),
    ]
