# Generated by Django 6.0.7 on 2026-07-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("adminpanel", "0023_syllabus_last_completed_slide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syllabuseditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="syllabuseditlog",
            name="syllabus",
            field=models.ForeignKey(
                help_text="The syllabus being modified (preserved even if syllabus is deleted)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edit_logs",
                to="adminpanel.syllabus",
            ),
        ),
    ]
